### ISSUE TITLE
error: projectGenerator path does not exist 

### ISSUE THREAD

**Issue by artificiel** [dimitre/ofbuild#4]
after compiling ofbuild and adjusting the `of.yml` `ofpath` to point to the current of-git tree that contains a compiled project generator, I run `% ofbuild` and get:
```
Build System for OpenFrameworks v.0.03
Dimitre Lima http://dmtr.org/

AeroFractal
current path		/Users/brtn/source_control/ofbuild
projectGenerator path does not exist 
```
to be clear:
```
ofbuild % `grep ofpath of.yml | awk {'print $2'} `/apps/projectGenerator/commandLine/bin/projectGenerator.app/Contents/MacOS/projectGenerator
[ error ] No arguments

	projectGenerator [options] pathName

if pathName exists, project is updated
if pathName doesn't exist, project is created
<etc...>
```

**Comment by dimitre** [comment]
is of.yml in your project folder?

**Comment by dimitre** [comment]
oh my bad, pushing a commit right now

**Comment by artificiel** [comment]
well, it's in an otherwise empty folder (say I'm starting a new project?)

edit: crossed-communication!

**Comment by dimitre** [comment]
you can pull now, I was using the wrong pg path (my branches)

**Comment by artificiel** [comment]
ok it works! I get a project but the ofxsyphon it downloaded is not ARC-compatible (I used your of.yml to test), but the project is otherwise legit.

will test more over the next few days.

**Comment by dimitre** [comment]
Great! yes I use the of_head branch. for now I'm using something like this:
not ideal
```yaml
addons:
- ofxMicroUI
- ofxTools
- -b of_head git@github.com:astellato/ofxSyphon.git
```
